const ytService = require('../services/ytService');
const path = require('path');
const fs = require('fs');

// Helper function to encode filename for Content-Disposition header
const encodeFilename = (filename) => {
    // Replace any non-ASCII characters with their percent-encoded equivalents
    return encodeURIComponent(filename)
        .replace(/['()]/g, escape) // Escape single quotes and parentheses
        .replace(/\*/g, '%2A'); // Escape asterisks
};

exports.getVideoInfo = async (req, res) => {
    try {
        const { url } = req.body;
        if (!url) {
            return res.status(400).json({ error: 'URL is required' });
        }
        const info = await ytService.getVideoInfo(url);
        res.json(info);
    } catch (error) {
        console.error('Error in getVideoInfo controller:', error);
        res.status(500).json({ error: error.message });
    }
};

exports.downloadVideo = async (req, res) => {
    try {
        const { url, format } = req.body;
        if (!url) {
            return res.status(400).json({ error: 'URL is required' });
        }

        // Set headers for streaming
        res.setHeader('Content-Type', 'application/octet-stream');
        res.setHeader('Transfer-Encoding', 'chunked');
        res.setHeader('Cache-Control', 'no-cache');
        res.setHeader('Connection', 'keep-alive');

        // Start the download stream
        await ytService.downloadVideo(url, format, res);
    } catch (error) {
        console.error('Error in downloadVideo controller:', error);
        if (!res.headersSent) {
            res.status(500).json({ 
                error: 'Failed to download video',
                details: error.message 
            });
        }
    }
};

exports.getAvailableSubtitles = async (req, res) => {
    try {
        const { url } = req.body;
        if (!url) {
            return res.status(400).json({ error: 'URL is required' });
        }
        const subtitles = await ytService.getAvailableSubtitles(url);
        res.json(subtitles);
    } catch (error) {
        console.error('Error in getAvailableSubtitles controller:', error);
        res.status(500).json({ error: error.message });
    }
};

exports.downloadSubtitles = async (req, res) => {
    try {
        const { url, language, autoGenerated } = req.body;
        if (!url || !language) {
            return res.status(400).json({ error: 'URL and language are required' });
        }

        // Set headers for streaming
        res.setHeader('Content-Type', 'application/octet-stream');
        res.setHeader('Transfer-Encoding', 'chunked');
        res.setHeader('Cache-Control', 'no-cache');
        res.setHeader('Connection', 'keep-alive');

        // Start the subtitle download stream
        await ytService.downloadSubtitles(url, language, autoGenerated, res);
    } catch (error) {
        console.error('Error in downloadSubtitles controller:', error);
        if (!res.headersSent) {
            res.status(500).json({ 
                error: 'Failed to download subtitles',
                details: error.message 
            });
        }
    }
}; 