import axios from 'axios';

const API_URL = 'http://localhost:5000/api';

const api = axios.create({
    baseURL: API_URL,
    headers: {
        'Content-Type': 'application/json',
    },
});

const handleError = (error) => {
    if (error.response) {
        // The request was made and the server responded with a status code
        // that falls out of the range of 2xx
        const message = error.response.data?.message || error.response.data?.error || 'Server error occurred';
        throw new Error(message);
    } else if (error.request) {
        // The request was made but no response was received
        throw new Error('No response from server. Please check if the server is running.');
    } else {
        // Something happened in setting up the request that triggered an Error
        throw new Error(error.message || 'An error occurred while making the request');
    }
};

export const getVideoInfo = async (url) => {
    try {
        const response = await axios.post(`${API_URL}/youtube/info`, { url });
        return response.data;
    } catch (error) {
        throw new Error(error.response?.data?.error || 'Failed to fetch video information');
    }
};

export const downloadVideo = async (url, format, onProgress) => {
    try {
        let lastProgress = 0;
        const response = await axios.post(
            `${API_URL}/youtube/download`,
            { url, format },
            {
                responseType: 'blob',
                onDownloadProgress: (progressEvent) => {
                    let progress;
                    if (progressEvent.total) {
                        progress = Math.round((progressEvent.loaded * 100) / progressEvent.total);
                    } else {
                        // If total is not available, estimate progress based on loaded bytes
                        progress = Math.min(Math.round((progressEvent.loaded / (1024 * 1024)) * 10), 99);
                    }
                    
                    // Only update if progress has increased
                    if (progress > lastProgress) {
                        lastProgress = progress;
                        onProgress?.(progress);
                    }
                },
            }
        );
        
        // Ensure we show 100% when complete
        onProgress?.(100);
        return response.data;
    } catch (error) {
        console.error('Download error:', error); // Debug log
        if (error.response?.data) {
            // Try to read the error message from the blob
            const reader = new FileReader();
            const errorText = await new Promise((resolve) => {
                reader.onload = () => resolve(reader.result);
                reader.readAsText(error.response.data);
            });
            throw new Error(errorText || 'Failed to download file');
        }
        throw new Error(error.message || 'Failed to download file');
    }
};

export const getAvailableSubtitles = async (url) => {
    try {
        const response = await axios.post(`${API_URL}/youtube/subtitles/list`, { url });
        return response.data;
    } catch (error) {
        throw new Error(error.response?.data?.error || 'Failed to fetch available subtitles');
    }
};

export const downloadSubtitles = async (url, language, autoGenerated = false, onProgress) => {
    try {
        let lastProgress = 0;
        const response = await axios.post(
            `${API_URL}/youtube/subtitles`,
            { url, language, autoGenerated },
            {
                responseType: 'blob',
                onDownloadProgress: (progressEvent) => {
                    let progress;
                    if (progressEvent.total) {
                        progress = Math.round((progressEvent.loaded * 100) / progressEvent.total);
                    } else {
                        // If total is not available, estimate progress based on loaded bytes
                        progress = Math.min(Math.round((progressEvent.loaded / (1024 * 1024)) * 10), 99);
                    }
                    
                    // Only update if progress has increased
                    if (progress > lastProgress) {
                        lastProgress = progress;
                        onProgress?.(progress);
                    }
                },
            }
        );
        
        // Ensure we show 100% when complete
        onProgress?.(100);
        return response.data;
    } catch (error) {
        console.error('Subtitle download error:', error); // Debug log
        if (error.response?.data) {
            // Try to read the error message from the blob
            const reader = new FileReader();
            const errorText = await new Promise((resolve) => {
                reader.onload = () => resolve(reader.result);
                reader.readAsText(error.response.data);
            });
            throw new Error(errorText || 'Failed to download subtitles');
        }
        throw new Error(error.message || 'Failed to download subtitles');
    }
}; 